image: node:5

cache:
  paths:
    - node_modules

stages:
  - build
  - deploy

build_lib:
  stage: build
  script:
    - npm install
    - node node_modules/bower/bin/bower install
    - npm run grunt
  artifacts:
    paths:
      - dist

deploy_lib:
  stage: deploy
  script:
      - cd deploy
      - npm install
      - node ./deploy_to_s3.js ../dist showcar-ui/$CI_BUILD_REF_NAME