image: bdadamas24/node-xvfb

cache:
  paths:
    - node_modules

stages:
  - build
  - deploy
  - documentation

before_script:
  - npm install -s
  - npm rebuild node-sass


pages:
  stage: documentation
  script:
    - npm run grunt docs && npm run grunt copy
  artifacts:
    paths:
      - public
  only:
    - master
    - develop


build_lib:
  stage: build
  only:
    - master
    - develop
  script:
    - npm run grunt
  artifacts:
    paths:
      - dist

deploy_lib:
  stage: deploy
  only:
    - master
    - develop
  script:
    - node deploy/deploy_to_s3.js "dist/+(index.html|showcar-ui.css|showcar-ui.js|showcar-ui.js.map)" showcar-ui/$CI_BUILD_REF_NAME/$CI_BUILD_REF
    - node deploy/deploy_to_s3.js "dist/index.html" showcar-ui/$CI_BUILD_REF_NAME/latest
    - node deploy/deploy_to_s3.js "src/html/showcar-ui-fragment.html" showcar-ui

sanity_test:
  stage: test
  only:
    - master
    - develop
  script:
    - xvfb-run --server-args="-screen 0 1024x768x24" npm run test-sanity