image: node:5

cache:
  paths:
    - node_modules/

build:
  script:
     - npm install -s
     - node node_modules/bower/bin/bower install
     - npm run grunt
  artifacts:
    paths:
      - dist
