image: node:5

cache:
  paths:
    - node_modules

stages:
  - build
  - deploy
  - documentation
  - test

pages:
  stage: documentation
  script:
    - npm install -s
    - npm run grunt docs
  artifacts:
    paths:
      - public
  only:
    - master
    - develop

build_lib:
  stage: build
  only:
    - master
    - develop
  script:
    - npm install -s
    - npm run grunt
  artifacts:
    paths:
      - dist

deploy_lib:
  stage: deploy
  only:
    - master
    - develop
  script:
    - cd deploy
    - npm install -s
    - node ./deploy_to_s3.js ../dist showcar-ui/$CI_BUILD_REF_NAME/$CI_BUILD_REF index.html,showcar-ui.css,showcar-ui.js,showcar-ui.js.map
    - node ./deploy_to_s3.js ../dist showcar-ui/$CI_BUILD_REF_NAME/latest index.html
    - node ./deploy_to_s3.js ../src/html showcar-ui showcar-ui-fragment.html

sanity_test:
  stage: test
  only:
    - master
    - develop
  script:
    - apt-get update &&\ apt-get install -y libgtk2.0-0 libgconf-2-4 \ libasound2 libxtst6 libxss1 libnss3 xvfb
    - Xvfb -ac -screen scrn 1280x2000x24 :9.0 & export DISPLAY=:9.0
    - npm install mocha -g --silent
    - npm install --silent
    - npm test