image: node:5

cache:
  paths:
    - node_modules

stages:
  - build
  - deploy

build_master:
  stage: build
  only:
    - master
  script:
    - npm install
    - node node_modules/bower/bin/bower install
    - npm run grunt
  artifacts:
    paths:
      - dist

build_develop:
  stage: build
  only:
    - develop
  script:
    - npm install
    - node node_modules/bower/bin/bower install
    - npm run grunt
  artifacts:
    paths:
      - dist

deploy_master:
  stage: deploy
  only:
      - master
  script:
      - cd deploy
      - npm install
      - node deploy_to_s3.js dist showcar-ui/prod

deploy_develop:
  stage: deploy
  only:
      - develop
  script:
      - cd deploy
      - npm install
      - node deploy_to_s3.js dist showcar-ui/latest