image: node:5

cache:
  paths:
    - node_modules

stages:
  - build
  - deploy

build_lib:
  stage: build
  only:
    - master
    - develop
  script:
    - npm install -s
    - node node_modules/bower/bin/bower install
    - npm run grunt
  artifacts:
    paths:
      - dist

deploy_lib:
  stage: deploy
  only:
      - master
      - develop
  script:
      - cd deploy
      - npm install -s
      - node ./deploy_to_s3.js ../dist showcar-ui/$CI_BUILD_REF_NAME/$CI_BUILD_REF
      - node ./deploy_to_s3.js ../dist showcar-ui/$CI_BUILD_REF_NAME/latest
