image: node:5

before_script:
  - npm cache clean

cache:
  paths:
    - node_modules/

stages:
  - build

build_master_and_deploy:
  stage: build
  only:
    - master
  script:
    - npm install
    - node node_modules/bower/bin/bower install
    - npm run grunt
  artifacts:
    paths:
      - dist

build_develop_and_deploy:
  stage: build
  only:
    - develop
  script:
    - npm install
    - node node_modules/bower/bin/bower install
    - npm run grunt
  artifacts:
    paths:
      - dist
