image: bdadamas24/node-xvfb

# cache:
#   paths:
#     - node_modules

stages:
  - build
  - deploy
  - test
  - documentation

pages:
  stage: documentation
  script:
    - npm install -s
    - npm run grunt docs
  artifacts:
    paths:
      - public
  only:
    - master
    - develop

build_lib:
  stage: build
  only:
    - master
    - develop
  script:
    - npm i
    - npm run grunt
  artifacts:
    paths:
      - dist

deploy_lib:
  stage: deploy
  only:
    - master
    - develop
  script:
    - cd deploy
    - npm install -s
    - node ./deploy_to_s3.js ../dist showcar-ui/$CI_BUILD_REF_NAME/$CI_BUILD_REF index.html,showcar-ui.css,showcar-ui.js,showcar-ui.js.map
    - node ./deploy_to_s3.js ../dist showcar-ui/$CI_BUILD_REF_NAME/latest index.html
    - node ./deploy_to_s3.js ../src/html showcar-ui showcar-ui-fragment.html

css_test:
  stage: test
  only:
    - master
    - develop
  script:
    - npm install -s
    - npm run test-css-reference
    - npm run test-css
  artifacts:
    paths:
      - backstop_data/bitmaps_test/**/*.png

sanity_test:
  stage: test
  only:
    - master
    - develop
  script:
    - npm install
    - xvfb-run --server-args="-screen 0 1024x768x24" npm test