language: node_js
node_js:
  - "7"

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - secure: "QfL8zDivnPlNcjbs3Fy9F86nL1gQ9m75zV6KsVxd/6Y4le3zonidMF9LOFU2aVzRW3A8W1fqLNBzlBJizLmDmRO78OLKnSRqIyUAYjLGVLx/aIVKsb9IqWLqeRNV4uTgyubYxemNKXa8jJWVJ2oObSPnUO2WwSOFSG+15YnvrnZBn13YnDkCfo8wbRhCg6rRP9ruyoV0DWa1PMf8WdEhOI2bliYA02jO9xA42N2HuEnmiScO+Q/bTzkcORcz2k9F2tUl8BtF3sBOgzIE853BsWKpXGotVMEvvpVplPTNuulYkRyTjetc6J06y17fW61EmDByroVIR6FgmNHf9wpeJf+RTOGFp/uNgLr7k87/dESAMbaKzTT09rSzp4hVFMBuPRY6u1g+OlK3rTkS9iFWMiOlRWhVa7uMB4s4pny/t5Hr/Xb3jfnjEuv+L0UiZ8zThOVaDGZ+ZP1C4bfdBP9GTeq+rXWDGs36yi5re3iNMfP77Zj1tfHVXMLk1EP3gF+nvsT2RsZxzYKXTSzMdo1VjX5WXUoegSJdRFIT7NO/+r8ffAcvHYkna0ouIRQVWJTNMP040S9Q8/ag0/ISGzsqs7738Qq8HhUyIhmKa9WeKOYo2nwo9wxDhp91ni4hZHRq/IZvSa+H+O681T/C+wG0WBzpR4N18N+p0tfOPV4YtS4="
    - secure: "QlPJQwynPbNLFeprD57TfAnYMQzXmqmZoVRSz5NzldrKqWpavl53UGavchPZhRqBm6Qx63urUYmSne5gt8HTcgqgUX/CZBk5dKpruT2Lb/ynG77NWA5skVcSFRL9/UsU1m++l2wCGLAK1LvcRpduzD0puWS4af91ZhCD7p+kLe1C9RG4Fz4VcssaGsW0nQ9kNxdHjWsN/Gu1PXfKcxHcsMZgHafaDvrsqLt/nVWeGJxJLwj29IvabDtaRPJFQfr9VNlOEECEmqbPzXa5tUA5+0I0BHHoAmwtMfNcRAbDAIjDQurD3i7G/7eHQP1ZQb3q3s/adbsKQVGtnMGknnYSiFvzOj4mL9hp8J7WXzvnkw7ow13Dzw7qGHu4DIi4ooFQ/TlVstP7cRDh8jep0LB5kN0d/fAPlNRWVDNLhCKZkhFkZrySVNCg5VeI6EmmkHJfroJuW75cKuAK6LQ5hUq1XghvYQwowiz3RM6OugyolblLmULP5mh4k2nCO/cO7tCN+NGngcBsrs/O/EP682VjVzJHZsevgXgVpEdpQKEkxiIsjcmcFedIBzqxbgeLkheQAfbOxdciPFX+US7POC4RBM/oWOYRymt9uYksJqU6iOfDZ57WiB0oqsc3vMQlVLBrB10OUm2K1milTpyw13K3wbo/6ukZZ+JI8ddqznaWr9o="

branches:
  except:
    - release
    - meta

notifications:
  email: false

before_install:
  - openssl aes-256-cbc -K $encrypted_8b283d52e7a6_key -iv $encrypted_8b283d52e7a6_iv -in as24-travis-key-private.enc -out release_key -d

script:
  - npm run build

after_success:
  # only run for master branch, we don't want to release PRs and other branches
  - 'if [ "$TRAVIS_PULL_REQUEST" != "true" ] && [ "$TRAVIS_BRANCH" == "master" ]; then bash ./travis_release.sh; fi'
