language: node_js
node_js:
  - "7"

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - secure: "rR4bne9n5vXIK4mnB+7XFAZgFCVZP9O+oIeGWZbEV19Rujw8eW0i7NUonREPKMsDuH9AznosG40+U2oGyVjnCObnAO2MD87K7hLxkGM4ablHl2v4NO1uYJ9rVN6hum1bP+3+ughmD+iD2bWDqNR+CXcg1rfZHPIV8ZcCC1XNiLwcCvDhdxZNMQEKzh3pxe+bXn3rCFIigo/fDRitSWVISzwvsyXwhffdivuylC+42POTYwuF42GBl4jauzESRfs7WsnWgATw4C3k5HjgKQdMQl/eqilsa2PFaxW1xD4oE/g3FlFJDw20xH1+HFxl+WBd6H3Z58Exyj8k4GvhoT6jvrUybrTHErlti7igwoRHa/C8Ux4NDFpS4PKhNHYtPAAiRJbWHDBdfWyHjp4VwW+IWrPtUV4pvaTEvq9pV7UzZIVKfZ+qHmh2NK/7SWOy7r+yV0F5N8JXtxjW9BGQFPN7k5flwIZOjTBf0Uo91xCGTlwJqbT7o005jkIWdq5SQ2Klpf8t8P167UsRNjB9zLaFO9P5eTSd5nmcS/V2UPDiMviSn+T7QLd+kwuzObCakpqB2T5zcEnb+mp7RrA+lQUdQsLNPZ0503mQI17WYnvCv/8DRkLfupkA3Vry0kdfqeH8DPxogPLpiDiJIEBWsDuT6EdgQqgKiaEMeMBJ+AotB4="

branches:
  except:
    - release

notifications:
  email: false

script:
  - npm run build

after_success:
  # only run for master branch, we don't want to release PRs and other branches
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then bash ./travis_release.sh; fi'

# deploy:
#  provider: script
#  script: travis_release.sh
#  on:
#    branch: master