language: node_js
node_js:
  - "7"

cache:
  yarn: true
  directories:
    - node_modules

branches:
  except:
    - release

notifications:
  email: false

script:
  - npm run grunt build
  - npm run grunt docs
  - npm run grunt copy:docs

after_success:
  # only run for master branch, we don't want to release PRs and other branches
  - 'bash ./travis_release.sh'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then bash ./travis_release.sh; fi'