language: node_js
node_js:
  - "7"

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - secure: "QfL8zDivnPlNcjbs3Fy9F86nL1gQ9m75zV6KsVxd/6Y4le3zonidMF9LOFU2aVzRW3A8W1fqLNBzlBJizLmDmRO78OLKnSRqIyUAYjLGVLx/aIVKsb9IqWLqeRNV4uTgyubYxemNKXa8jJWVJ2oObSPnUO2WwSOFSG+15YnvrnZBn13YnDkCfo8wbRhCg6rRP9ruyoV0DWa1PMf8WdEhOI2bliYA02jO9xA42N2HuEnmiScO+Q/bTzkcORcz2k9F2tUl8BtF3sBOgzIE853BsWKpXGotVMEvvpVplPTNuulYkRyTjetc6J06y17fW61EmDByroVIR6FgmNHf9wpeJf+RTOGFp/uNgLr7k87/dESAMbaKzTT09rSzp4hVFMBuPRY6u1g+OlK3rTkS9iFWMiOlRWhVa7uMB4s4pny/t5Hr/Xb3jfnjEuv+L0UiZ8zThOVaDGZ+ZP1C4bfdBP9GTeq+rXWDGs36yi5re3iNMfP77Zj1tfHVXMLk1EP3gF+nvsT2RsZxzYKXTSzMdo1VjX5WXUoegSJdRFIT7NO/+r8ffAcvHYkna0ouIRQVWJTNMP040S9Q8/ag0/ISGzsqs7738Qq8HhUyIhmKa9WeKOYo2nwo9wxDhp91ni4hZHRq/IZvSa+H+O681T/C+wG0WBzpR4N18N+p0tfOPV4YtS4="
    # - secure: "rR4bne9n5vXIK4mnB+7XFAZgFCVZP9O+oIeGWZbEV19Rujw8eW0i7NUonREPKMsDuH9AznosG40+U2oGyVjnCObnAO2MD87K7hLxkGM4ablHl2v4NO1uYJ9rVN6hum1bP+3+ughmD+iD2bWDqNR+CXcg1rfZHPIV8ZcCC1XNiLwcCvDhdxZNMQEKzh3pxe+bXn3rCFIigo/fDRitSWVISzwvsyXwhffdivuylC+42POTYwuF42GBl4jauzESRfs7WsnWgATw4C3k5HjgKQdMQl/eqilsa2PFaxW1xD4oE/g3FlFJDw20xH1+HFxl+WBd6H3Z58Exyj8k4GvhoT6jvrUybrTHErlti7igwoRHa/C8Ux4NDFpS4PKhNHYtPAAiRJbWHDBdfWyHjp4VwW+IWrPtUV4pvaTEvq9pV7UzZIVKfZ+qHmh2NK/7SWOy7r+yV0F5N8JXtxjW9BGQFPN7k5flwIZOjTBf0Uo91xCGTlwJqbT7o005jkIWdq5SQ2Klpf8t8P167UsRNjB9zLaFO9P5eTSd5nmcS/V2UPDiMviSn+T7QLd+kwuzObCakpqB2T5zcEnb+mp7RrA+lQUdQsLNPZ0503mQI17WYnvCv/8DRkLfupkA3Vry0kdfqeH8DPxogPLpiDiJIEBWsDuT6EdgQqgKiaEMeMBJ+AotB4="
    - secure: "QlPJQwynPbNLFeprD57TfAnYMQzXmqmZoVRSz5NzldrKqWpavl53UGavchPZhRqBm6Qx63urUYmSne5gt8HTcgqgUX/CZBk5dKpruT2Lb/ynG77NWA5skVcSFRL9/UsU1m++l2wCGLAK1LvcRpduzD0puWS4af91ZhCD7p+kLe1C9RG4Fz4VcssaGsW0nQ9kNxdHjWsN/Gu1PXfKcxHcsMZgHafaDvrsqLt/nVWeGJxJLwj29IvabDtaRPJFQfr9VNlOEECEmqbPzXa5tUA5+0I0BHHoAmwtMfNcRAbDAIjDQurD3i7G/7eHQP1ZQb3q3s/adbsKQVGtnMGknnYSiFvzOj4mL9hp8J7WXzvnkw7ow13Dzw7qGHu4DIi4ooFQ/TlVstP7cRDh8jep0LB5kN0d/fAPlNRWVDNLhCKZkhFkZrySVNCg5VeI6EmmkHJfroJuW75cKuAK6LQ5hUq1XghvYQwowiz3RM6OugyolblLmULP5mh4k2nCO/cO7tCN+NGngcBsrs/O/EP682VjVzJHZsevgXgVpEdpQKEkxiIsjcmcFedIBzqxbgeLkheQAfbOxdciPFX+US7POC4RBM/oWOYRymt9uYksJqU6iOfDZ57WiB0oqsc3vMQlVLBrB10OUm2K1milTpyw13K3wbo/6ukZZ+JI8ddqznaWr9o="
branches:
  except:
    - release

notifications:
  email: false

script:
  - npm run build

after_success:
  # only run for master branch, we don't want to release PRs and other branches
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then bash ./travis_release.sh; fi'

# deploy:
#  provider: script
#  script: travis_release.sh
#  on:
#    branch: master