language: node_js
node_js:
  - "7"

cache:
  yarn: true
  directories:
    - node_modules

addons:
  sauce_connect: true
  apt:
    packages:
      - oracle-java8-set-default

env:
  global:
    - secure: "QlPJQwynPbNLFeprD57TfAnYMQzXmqmZoVRSz5NzldrKqWpavl53UGavchPZhRqBm6Qx63urUYmSne5gt8HTcgqgUX/CZBk5dKpruT2Lb/ynG77NWA5skVcSFRL9/UsU1m++l2wCGLAK1LvcRpduzD0puWS4af91ZhCD7p+kLe1C9RG4Fz4VcssaGsW0nQ9kNxdHjWsN/Gu1PXfKcxHcsMZgHafaDvrsqLt/nVWeGJxJLwj29IvabDtaRPJFQfr9VNlOEECEmqbPzXa5tUA5+0I0BHHoAmwtMfNcRAbDAIjDQurD3i7G/7eHQP1ZQb3q3s/adbsKQVGtnMGknnYSiFvzOj4mL9hp8J7WXzvnkw7ow13Dzw7qGHu4DIi4ooFQ/TlVstP7cRDh8jep0LB5kN0d/fAPlNRWVDNLhCKZkhFkZrySVNCg5VeI6EmmkHJfroJuW75cKuAK6LQ5hUq1XghvYQwowiz3RM6OugyolblLmULP5mh4k2nCO/cO7tCN+NGngcBsrs/O/EP682VjVzJHZsevgXgVpEdpQKEkxiIsjcmcFedIBzqxbgeLkheQAfbOxdciPFX+US7POC4RBM/oWOYRymt9uYksJqU6iOfDZ57WiB0oqsc3vMQlVLBrB10OUm2K1milTpyw13K3wbo/6ukZZ+JI8ddqznaWr9o="

branches:
  except:
    - release
    - meta

notifications:
  email: false

script:
  - npm run build
  - npm run docs
  # - SAUCE_TUNNEL_ID=$TRAVIS_JOB_NUMBER npm run test-galen
  - SAUCE_TUNNEL_ID=$TRAVIS_JOB_NUMBER npm run test-galen

after_success:
  # only run for master branch, we don't want to release PRs and other branches
  - 'if [ "$TRAVIS_PULL_REQUEST" != "true" ] && [ "$TRAVIS_BRANCH" == "master" ]; then openssl aes-256-cbc -K $encrypted_d70c34fb3c42_key -iv $encrypted_d70c34fb3c42_iv -in travis-release-key.enc -out release_key -d; fi'
  # deploy to release branch
  - 'if [ "$TRAVIS_PULL_REQUEST" != "true" ] && [ "$TRAVIS_BRANCH" == "master" ]; then bash ./travis_release.sh; fi'
  # deploy to docs branch (gh-pages)
  - 'if [ "$TRAVIS_PULL_REQUEST" != "true" ] && [ "$TRAVIS_BRANCH" == "master" ]; then bash ./travis_docs.sh; fi'
