default:
  tasks:
    - build

build:
  description: 'Build the distribution'
  tasks:
    - 'copy:polyfills'
    - 'sass:dist'
    - 'pleeease:dist'
    - 'webpack:dist'
    # - 'generate-polyfills'
    - 'replace:fragment'

docs:
  description: 'Build the documentation'
  tasks:
    - 'copy:docs'
    - 'sass:docs'
    - 'pleeease:docs'
    - 'webpack:docs'
    - 'assemble:docs'

test-local:
  tasks:
    - 'selenium_standalone:local:install'
    - 'selenium_standalone:local:start'
    - 'webdriver:local'
    - 'selenium_standalone:local:stop'

test-cbt:
  tasks:
    - 'webdriver:cbt'
